// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzeL95aROrUTRbfeJ-jcRNC66Nri0NDaM',
    appId: '1:811323347917:web:d99c28d85dfe8257416a84',
    messagingSenderId: '811323347917',
    projectId: 'madadgaar-1122',
    authDomain: 'madadgaar-1122.firebaseapp.com',
    storageBucket: 'madadgaar-1122.firebasestorage.app',
    measurementId: 'G-QQSM62371F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEadg6Xmi3BFpCzy24temVlGN8FzLEs0A',
    appId: '1:811323347917:android:632ec88124414bfc416a84',
    messagingSenderId: '811323347917',
    projectId: 'madadgaar-1122',
    storageBucket: 'madadgaar-1122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ6NDGmoM99izbfS2dbPHcH8Z1WYIZcmA',
    appId: '1:811323347917:ios:610cecefdc8b9b11416a84',
    messagingSenderId: '811323347917',
    projectId: 'madadgaar-1122',
    storageBucket: 'madadgaar-1122.firebasestorage.app',
    iosBundleId: 'com.example.madadgaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ6NDGmoM99izbfS2dbPHcH8Z1WYIZcmA',
    appId: '1:811323347917:ios:610cecefdc8b9b11416a84',
    messagingSenderId: '811323347917',
    projectId: 'madadgaar-1122',
    storageBucket: 'madadgaar-1122.firebasestorage.app',
    iosBundleId: 'com.example.madadgaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzeL95aROrUTRbfeJ-jcRNC66Nri0NDaM',
    appId: '1:811323347917:web:c97c750482277ac5416a84',
    messagingSenderId: '811323347917',
    projectId: 'madadgaar-1122',
    authDomain: 'madadgaar-1122.firebaseapp.com',
    storageBucket: 'madadgaar-1122.firebasestorage.app',
    measurementId: 'G-JN6W3VDGFG',
  );
}
